#########################
# Model Configurations  # 4-4-4 same dim
#########################

LOG: '../log'
DATASET: 'G'

WANDB:
    PROJ_NAME: 'CHILD'
    LOG_NAME: ''
  
VAE:
    CPU: 8
    GPU: 1
    TRAIN_BS: 64
    VAL_BS: 1024
    EPOCHS: 5
    N_VAL_SAMPLES: 1024
    NCLASS: 15
    EMBED_DIM: 2
    LAG: 1
    LR: 5.0e-5
    BETA: 3.0e-3
    GAMMA: 1.0e-2
    THETA: 1.0e-4
    # THETA: 0.0
    INPUT_DIM: 4
    LATENT_DIM: 12
    LATENT_DIM_FIX: 12
    LATENT_DIM_CHANGE: 0
    N_MEA: 7
    Z_DIM_LIST: [4, 4, 4]
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE
    FLEXIBLE_SPARTSITY:
        ENABLE: FALSE

MCC:
    FREQ: 0.5
    CORR: 'Spearman' #'Pearson' # 'Spearman'
