#########################
# Model Configurations  # 4-4-4 same dim
#########################

LOG: '../log'
DATASET: 'G'

WANDB:
    PROJ_NAME: 'CHILD'
    LOG_NAME: ''
  
VAE:
    CPU: 8
    GPU: 4
    TRAIN_BS: 64
    VAL_BS: 1024
    EPOCHS: 5
    N_VAL_SAMPLES: 1024
    NCLASS: 15
    EMBED_DIM: 2
    LAG: 1
    LR: 1.0e-6
    BETA: 0.0
    GAMMA: 0.0
    THETA: 1.0e-4
    # THETA: 0.0
    INPUT_DIM: 10
    LATENT_DIM: 30
    LATENT_DIM_FIX: 30
    LATENT_DIM_CHANGE: 0
    Z_DIM_LIST: [10, 10, 10]
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE
    N_MEA: 5
    FLEXIBLE_SPARTSITY:
        ENABLE: FALSE

MCC:
    FREQ: 0.5
    CORR: 'Spearman' #'Pearson' # 'Spearman'
