#########################
# Model Configurations  # 1-2-4 varying dim with tanh MLP mixing
#########################

LOG: '../log'
DATASET: 'O'

WANDB:
    PROJ_NAME: 'CHILD'
    LOG_NAME: 'O_tanh_mlp'
  
VAE:
    CPU: 8
    GPU: 1
    TRAIN_BS: 64
    VAL_BS: 1024
    EPOCHS: 10
    N_VAL_SAMPLES: 1024
    NCLASS: 15
    EMBED_DIM: 2
    LAG: 1
    LR: 3.0e-4
    BETA: 8.0e-3
    GAMMA: 8.0e-3
    THETA: 2.3e-3
    INPUT_DIM: 4
    LATENT_DIM: 7
    LATENT_DIM_FIX: 7
    LATENT_DIM_CHANGE: 0
    Z_DIM_LIST: [1, 2, 4]
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE
    N_MEA: 5
    FLEXIBLE_SPARTSITY:
        ENABLE: TRUE
        HIST: [2.0, 7.0, 11.0]
        INST: [0.0, 1.0, 4.0]

MCC:
    FREQ: 0.5
    CORR: 'Spearman'