#########################
# Model Configurations  # 4-4-4 same dim
#########################

LOG: '../log'
DATASET: 'G'

WANDB:
    ENTITY: 'minghao_workaholic'
    PROJ_NAME: 'child'
    LOG_NAME: 'new_G_dim18'
  
VAE:
    CPU: 8
    GPU: 4
    TRAIN_BS: 64
    VAL_BS: 1024
    EPOCHS: 5
    N_VAL_SAMPLES: 1024
    NCLASS: 15
    EMBED_DIM: 2
    LAG: 1
    LR: 5.0e-5
    BETA: 3.0e-3
    GAMMA: 1.0e-2
    THETA: 1.0e-4
    # THETA: 0.0
    INPUT_DIM: 8
    LATENT_DIM: 24
    LATENT_DIM_FIX: 24
    LATENT_DIM_CHANGE: 0
    Z_DIM_LIST: [8, 8, 8]
    BIAS: FALSE
    ENC:
        HIDDEN_DIM: 128
    DEC:
        HIDDEN_DIM: 128
        DIST: 'gaussian'
    PIN: TRUE
    N_MEA: 5
    FLEXIBLE_SPARTSITY:
        ENABLE: FALSE

MCC:
    FREQ: 0.5
    CORR: 'Spearman' #'Pearson' # 'Spearman'
